spring.application.name=spring-boot-tutorial
spring.datasource.url=jdbc:postgresql://localhost:5332/spring
spring.datasource.username=user
spring.datasource.password=password

#Drops the database on every run
spring.jpa.hibernate.ddl-auto=create-drop

#Shows the "formated" sql in the runtime compilator
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
